<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>model – Predicting Educational Attainment</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f68e1890bf49daf0bb4e7e0e419a9468.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Predicting Educational Attainment</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./exploratory.html"> 
<span class="menu-text">Visualization</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./model.html" aria-current="page"> 
<span class="menu-text">DGM &amp; Predictive Model</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./sources.html"> 
<span class="menu-text">Sources</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#data-generating-mechanism-dgm-formulations" id="toc-data-generating-mechanism-dgm-formulations" class="nav-link active" data-scroll-target="#data-generating-mechanism-dgm-formulations">1. Data Generating Mechanism (DGM) Formulations</a></li>
  <li><a href="#model-estimation-95-confidence-intervals" id="toc-model-estimation-95-confidence-intervals" class="nav-link" data-scroll-target="#model-estimation-95-confidence-intervals">2. Model Estimation &amp; 95% Confidence Intervals</a></li>
  <li><a href="#visualizing-uncertainty" id="toc-visualizing-uncertainty" class="nav-link" data-scroll-target="#visualizing-uncertainty">3. Visualizing Uncertainty</a></li>
  <li><a href="#the-dgm-in-action" id="toc-the-dgm-in-action" class="nav-link" data-scroll-target="#the-dgm-in-action">4. The DGM in Action</a></li>
  <li><a href="#formal-predictive-verdict" id="toc-formal-predictive-verdict" class="nav-link" data-scroll-target="#formal-predictive-verdict">5. Formal Predictive Verdict</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="our-verdict" class="level1 unlisted hero-banner">
<h1 class="unlisted">Our Verdict</h1>
<p class="hero-subtitle">
Formal Data Generating Mechanisms, Likelihood Ratio Tests, 95% Confidence Intervals &amp; Empirical Verdict
</p>
</section>
<hr>
<section id="data-generating-mechanism-dgm-formulations" class="level2">
<h2 class="anchored" data-anchor-id="data-generating-mechanism-dgm-formulations">1. Data Generating Mechanism (DGM) Formulations</h2>
<p>To predict individual educational attainment (<span class="math inline">\(Y_{\text{educ}}\)</span>) conditioned on socio-demographic origin traits, we establish two formal statistical Data Generating Mechanisms: a primary <strong>Multinomial Logistic DGM</strong> for categorical milestone tiers and an <strong>Ordinary Least Squares (OLS) DGM</strong> for continuous schooling years.</p>
<section id="multinomial-logistic-dgm" class="level3">
<h3 class="anchored" data-anchor-id="multinomial-logistic-dgm">1.1 Multinomial Logistic DGM</h3>
<p>We model the conditional log-odds of an individual attaining educational tier <span class="math inline">\(k \in \{\text{Some College}, \text{Bachelor Degree}, \text{Graduate Degree}\}\)</span> relative to baseline <span class="math inline">\(K_0 = \text{High School or Less}\)</span>:</p>
<p><span class="math display">\[\ln\left(\frac{P(Y_{\text{educ}} = k \mid \mathbf{X})}{P(Y_{\text{educ}} = K_0 \mid \mathbf{X})}\right) = \beta_{k0} + \boldsymbol{\beta}_k^T \mathbf{X}\]</span></p>
<p>where <span class="math inline">\(\mathbf{X}\)</span> represents the vector of statistically selected socio-demographic covariates:</p>
<p><span class="math display">\[\mathbf{X} = \Big[ \text{parent\_educ}, \text{incom16}, \text{sibs}, \text{childs}, \text{age}, \text{year}, \text{sex}, \text{race}, \text{res16}, \text{family16}, \text{born}, \text{parborn} \Big]^T\]</span></p>
<p>The predicted conditional probability <span class="math inline">\(P(Y_{\text{educ}} = k \mid \mathbf{X})\)</span> across all 4 attainment levels is determined via the soft-max transformation:</p>
<p><span class="math display">\[P(Y_{\text{educ}} = k \mid \mathbf{X}) = \frac{\exp\left(\beta_{k0} + \boldsymbol{\beta}_k^T \mathbf{X}\right)}{1 + \sum_{j=1}^{3} \exp\left(\beta_{j0} + \boldsymbol{\beta}_j^T \mathbf{X}\right)}\]</span></p>
<hr>
</section>
<section id="linear-regression-dgm" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression-dgm">1.2 Linear Regression DGM</h3>
<p>As a comparative benchmark, we model completed years of schooling (<span class="math inline">\(Y_{\text{years}} \in [0, 20]\)</span>) as a continuous conditional expectation:</p>
<p><span class="math display">\[Y_{\text{years}} = \beta_0 + \boldsymbol{\beta}^T \mathbf{X} + \varepsilon, \quad \varepsilon \sim \mathcal{N}(0, \sigma^2)\]</span></p>
<hr>
</section>
</section>
<section id="model-estimation-95-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="model-estimation-95-confidence-intervals">2. Model Estimation &amp; 95% Confidence Intervals</h2>
<blockquote class="blockquote">
<p><strong>Note</strong>: The following tables (3.2 &amp; 3.3) are shortened tables with only the most statistically significant covariates. The complete parameter table across all predictors and outcome tiers can be found in Section 3 of the <a href="./sources.html">Sources</a> tab.</p>
</blockquote>
<section id="final-multinomial-logistic-model-parameters" class="level3">
<h3 class="anchored" data-anchor-id="final-multinomial-logistic-model-parameters">2.1 Final Multinomial Logistic Model Parameters</h3>
<p>We estimate multinomial parameters and calculate Odds Ratios (<span class="math inline">\(\text{OR} = \exp(\beta)\)</span>) with exact 95% Confidence Intervals using <code>broom::tidy(conf.int = TRUE, exponentiate = TRUE)</code>.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3.2: Multinomial Odds Ratios &amp; 95% Confidence Intervals for Bachelor’s Degree Attainment (Ref: High School or Less)</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 41%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Outcome Tier</th>
<th style="text-align: left;">Predictor Variable</th>
<th style="text-align: right;">Odds Ratio (OR)</th>
<th style="text-align: left;">p-value</th>
<th style="text-align: right;">95% CI Lower</th>
<th style="text-align: right;">95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bachelor Degree</td>
<td style="text-align: left;">Parental Education (Per Year)</td>
<td style="text-align: right;">1.333</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">1.318</td>
<td style="text-align: right;">1.347</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bachelor Degree</td>
<td style="text-align: left;">Childhood Relative Income (Tier 1-5)</td>
<td style="text-align: right;">1.172</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">1.132</td>
<td style="text-align: right;">1.214</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bachelor Degree</td>
<td style="text-align: left;">Sibling Count (Per Sibling)</td>
<td style="text-align: right;">0.854</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">0.840</td>
<td style="text-align: right;">0.868</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bachelor Degree</td>
<td style="text-align: left;">Residence: Big-City Suburb (vs Farm)</td>
<td style="text-align: right;">1.420</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">1.362</td>
<td style="text-align: right;">1.481</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bachelor Degree</td>
<td style="text-align: left;">Single Parent Family (vs Both Parents)</td>
<td style="text-align: right;">0.562</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">0.530</td>
<td style="text-align: right;">0.596</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bachelor Degree</td>
<td style="text-align: left;">Parents Nativity: Neither U.S. Born (vs Both)</td>
<td style="text-align: right;">1.770</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">1.713</td>
<td style="text-align: right;">1.828</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>What the Numbers Mean:</strong> Each Odds Ratio (OR) measures the association between a covariate and an outcome. An OR &gt; 1 indicates a higher likelihood of the outcome (specifically, a <span class="math inline">\((OR - 1) \times 100\%\)</span> increase), while an OR &lt; 1 indicates a lower likelihood.</p>
<p><strong>Example:</strong> In this table, each additional year of parental education is associated with a 33.3% higher chance of attaining a Bachelor’s degree.</p>
<hr>
</section>
<section id="ols-baseline-model-parameters" class="level3">
<h3 class="anchored" data-anchor-id="ols-baseline-model-parameters">2.2 OLS Baseline Model Parameters</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3.3: Primary OLS Model Parameters &amp; 95% Confidence Intervals (Variables Featured in Predictive Verdict)</caption>
<colgroup>
<col style="width: 44%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: right;">Estimate (β)</th>
<th style="text-align: left;">p-value</th>
<th style="text-align: right;">95% CI Lower</th>
<th style="text-align: right;">95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Parental Education (Per Year)</td>
<td style="text-align: right;">0.326</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">0.318</td>
<td style="text-align: right;">0.333</td>
</tr>
<tr class="even">
<td style="text-align: left;">Childhood Relative Income (Tier 1-5)</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">0.157</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sibling Count (Per Sibling)</td>
<td style="text-align: right;">-0.182</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">-0.195</td>
<td style="text-align: right;">-0.170</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residence Origin: Big-City Suburb</td>
<td style="text-align: right;">0.246</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">0.163</td>
<td style="text-align: right;">0.329</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Family Structure: Single Parent</td>
<td style="text-align: right;">-0.607</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">-0.672</td>
<td style="text-align: right;">-0.541</td>
</tr>
<tr class="even">
<td style="text-align: left;">Parents Nativity: Neither U.S. Born</td>
<td style="text-align: right;">0.508</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: right;">0.401</td>
<td style="text-align: right;">0.615</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>What the Numbers Mean:</strong> Each Estimate (<span class="math inline">\(\beta\)</span>) measures the slope between a covariate and the outcome. For every 1-unit increase in the covariate, the outcome is predicted to change by the estimated amount, holding all other variables constant.</p>
<p><strong>Example:</strong> In this table, a 1-year increase in parental education is associated with 0.326 additional years of education.</p>
<hr>
</section>
</section>
<section id="visualizing-uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-uncertainty">3. Visualizing Uncertainty</h2>
<p>To evaluate parameter estimates and quantify uncertainty visually, we construct point-range error-bar plots for both statistical models.</p>
<section id="multinomial-logistic-model-uncertainty" class="level3">
<h3 class="anchored" data-anchor-id="multinomial-logistic-model-uncertainty">3.1 Multinomial Logistic Model Uncertainty</h3>
<p>Figure 3.1 illustrates the Odds Ratios (<span class="math inline">\(\text{OR} = \exp(\beta)\)</span>) and exact 95% Confidence Intervals for predicting <strong>Bachelor Degree</strong> and <strong>Graduate Degree</strong> attainment relative to the High School baseline tier.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="model_files/figure-html/forest-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 3.1: Multinomial Logistic Model Odds Ratios &amp; 95% Confidence Intervals for Bachelor’s and Graduate Degrees (Ref: High School or Less).</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="ols-regression-model-uncertainty" class="level3">
<h3 class="anchored" data-anchor-id="ols-regression-model-uncertainty">3.2 OLS Regression Model Uncertainty</h3>
<p>Figure 3.2 displays continuous linear parameter estimates (<span class="math inline">\(\beta\)</span>) and 95% Confidence Intervals for predicting total completed schooling years (<span class="math inline">\(Y_{\text{years}}\)</span>). In linear OLS regression, the null baseline hypothesis corresponds to <span class="math inline">\(\beta = 0\)</span> (no linear effect on total schooling years).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="model_files/figure-html/ols-forest-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 3.2: OLS Linear Regression Parameter Estimates (β) &amp; 95% Confidence Intervals for Completed Schooling Years.</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="the-dgm-in-action" class="level2">
<h2 class="anchored" data-anchor-id="the-dgm-in-action">4. The DGM in Action</h2>
<p>To demonstrate how our statistical model works in practice, we construct two contrasting individual profiles with different childhood socio-demographic backgrounds and use the multinomial model to predict their exact likelihood of achieving a Bachelor’s degree (and other degree tiers), alongside OLS continuous schooling predictions.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3.4: Model-Predicted Educational Attainment Probabilities &amp; Expected Schooling Years for Two Individual Profiles</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 38%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model Outcome Tier / Metric</th>
<th style="text-align: left;">Individual A (Advantaged Profile)</th>
<th style="text-align: left;">Individual B (Disadvantaged Profile)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Childhood Background Characteristics</td>
<td style="text-align: left;">College-educated parents, Income Far Above Avg, Two parents, Suburban, 1 Sibling</td>
<td style="text-align: left;">Middle-school parents, Income Far Below Avg, Single parent, Farm origin, 4 Siblings</td>
</tr>
<tr class="even">
<td style="text-align: left;">High School or Less (Multinomial Probability)</td>
<td style="text-align: left;">6.7%</td>
<td style="text-align: left;">70.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Some College (Multinomial Probability)</td>
<td style="text-align: left;">25.4%</td>
<td style="text-align: left;">21.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bachelor Degree (Multinomial Probability)</td>
<td style="text-align: left;">39.7%</td>
<td style="text-align: left;">5.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Graduate Degree (Multinomial Probability)</td>
<td style="text-align: left;">28.1%</td>
<td style="text-align: left;">3.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Predicted Total Schooling Years (OLS Model)</td>
<td style="text-align: left;">16.7 Years</td>
<td style="text-align: left;">11.9 Years</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><p><strong>Individual A</strong>: Driven by high parental education (16 years) and economic stability, this individual has a <strong>39.7% chance</strong> of attaining a Bachelor’s degree, an overall <strong>67.9% chance</strong> of completing college (Bachelor’s or Graduate), and an expected <strong>16.7 total years of schooling</strong> from the OLS model.</p></li>
<li><p><strong>Individual B</strong>: Facing cumulative socio-economic headwinds, this individual has only a <strong>5.1% chance</strong> of attaining a Bachelor’s degree (<strong>70.4% chance</strong> of stopping at High School or less), and an expected <strong>11.9 total years of schooling</strong> from the OLS model.</p></li>
</ul>
<hr>
</section>
<section id="formal-predictive-verdict" class="level2">
<h2 class="anchored" data-anchor-id="formal-predictive-verdict">5. Formal Predictive Verdict</h2>
<section id="predictive-modeling-verdict-key-summary" class="level3">
<h3 class="anchored" data-anchor-id="predictive-modeling-verdict-key-summary">📊 Predictive Modeling Verdict &amp; Key Summary</h3>
<section id="model-accuracy-evaluation" class="level4">
<h4 class="anchored" data-anchor-id="model-accuracy-evaluation">1. Model Accuracy Evaluation</h4>
<p>To evaluate how accurately our models predict educational outcomes, we test their performance across all <span class="math inline">\(N = 48,360\)</span> survey respondents:</p>
<ul>
<li><strong>College Degree Prediction Accuracy (72.3%)</strong>: When predicting whether an individual will successfully earn a <strong>Bachelor’s degree or higher</strong> versus a non-college path, our multinomial model achieves <strong>72.3% overall accuracy</strong>.</li>
<li><strong>OLS Continuous Schooling Accuracy (<span class="math inline">\(\pm 2\)</span> Years Tolerance: 60.8%)</strong>: When evaluating whether the Ordinary Least Squares (OLS) model predicts total completed schooling within <strong><span class="math inline">\(\pm 2.0\)</span> years</strong> of the actual answer, it achieves <strong>60.8% accuracy</strong>, with an overall Mean Absolute Error (MAE) of <strong>1.95 years</strong>.</li>
<li><strong>What This Means</strong>: Imagine taking a room of 100 people. By only looking at basic background information from their childhood—such as their parents’ education level, household income tier, family structure, and sibling count:
<ul>
<li>Our multinomial model correctly classifies whether <strong>72 out of 100 people</strong> will graduate from college.</li>
<li>Our OLS linear model predicts total completed schooling within <strong><span class="math inline">\(\pm 2\)</span> years</strong> for <strong>61 out of 100 people</strong>, missing by an average of under 2 years (<span class="math inline">\(1.95\)</span> years MAE).</li>
</ul></li>
</ul>
</section>
<section id="answer-to-central-predictive-question" class="level4">
<h4 class="anchored" data-anchor-id="answer-to-central-predictive-question">2. Answer to Central Predictive Question</h4>
<blockquote class="blockquote">
<p><strong>“To what extent do social, economic, and demographic factors jointly predict whether an individual achieves a specific education level such as a Bachelor’s degree in the United States?”</strong></p>
</blockquote>
<ol type="1">
<li><strong>Parental Education is the Single Strongest Predictor</strong>:
<ul>
<li><strong>Multinomial Degree Completion Odds</strong>: Every additional year of parental schooling increases an individual’s odds of earning a Bachelor’s degree by <strong>33.3%</strong> (<span class="math inline">\(\text{OR} = 1.333\)</span>, <span class="math inline">\(95\%\text{ CI: }[1.319, 1.348]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) and a Graduate degree by <strong>40.5%</strong> (<span class="math inline">\(\text{OR} = 1.405\)</span>, <span class="math inline">\(95\%\text{ CI: }[1.388, 1.423]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</li>
<li><strong>OLS Continuous Schooling Impact</strong>: In the linear model, each additional year of parental education directly increases completed schooling by <strong>+0.326 years</strong> (<span class="math inline">\(95\%\text{ CI: }[0.318, 0.333]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</li>
</ul></li>
<li><strong>Childhood Household Income &amp; Family Dynamics</strong>:
<ul>
<li><strong>Relative Household Income</strong>: Higher childhood relative income significantly increases Bachelor’s degree completion odds by <strong>16.8% per income tier</strong> (<span class="math inline">\(\text{OR} = 1.168\)</span>, <span class="math inline">\(95\%\text{ CI: }[1.129, 1.209]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) and adds <strong>+0.129 years</strong> of completed schooling (<span class="math inline">\(95\%\text{ CI: }[0.101, 0.157]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</li>
<li><strong>Single-Parent Family Structure</strong>: Growing up in a single-parent family reduces Bachelor’s degree completion odds by <strong>43.8%</strong> (<span class="math inline">\(\text{OR} = 0.562\)</span>, <span class="math inline">\(95\%\text{ CI: }[0.530, 0.596]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) and reduces total completed schooling by <strong>-0.607 years</strong> (<span class="math inline">\(95\%\text{ CI: }[-0.672, -0.541]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</li>
<li><strong>Sibling Size</strong>: Each additional sibling reduces Bachelor’s degree completion odds by <strong>14.6%</strong> (<span class="math inline">\(\text{OR} = 0.854\)</span>, <span class="math inline">\(95\%\text{ CI: }[0.840, 0.868]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) and reduces total schooling by <strong>-0.182 years per sibling</strong> (<span class="math inline">\(95\%\text{ CI: }[-0.195, -0.170]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</li>
</ul></li>
<li><strong>Geographic &amp; Immigrant Origin Dynamics</strong>:
<ul>
<li><strong>Suburban &amp; Large City Origins</strong>: Growing up in a suburban environment increases Bachelor’s degree odds by <strong>41.7%</strong> compared to rural origins (<span class="math inline">\(\text{OR} = 1.417\)</span>, <span class="math inline">\(95\%\text{ CI: }[1.358, 1.479]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) and adds <strong>+0.246 years</strong> of completed schooling (<span class="math inline">\(95\%\text{ CI: }[0.163, 0.329]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</li>
<li><strong>Parental Immigrant Status</strong>: Children of immigrant parents whose parents were not born in the U.S. exhibit <strong>77.1% higher odds</strong> of completing a Bachelor’s degree (<span class="math inline">\(\text{OR} = 1.771\)</span>, <span class="math inline">\(95\%\text{ CI: }[1.714, 1.830]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) and gain <strong>+0.508 years</strong> of total schooling (<span class="math inline">\(95\%\text{ CI: }[0.401, 0.615]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</li>
</ul></li>
</ol>
</section>
<section id="strategic-policy-recommendation" class="level4">
<h4 class="anchored" data-anchor-id="strategic-policy-recommendation">3. Strategic Policy Recommendation</h4>
<p>Because parental education and childhood economic status exert strong conditional effects on educational outcomes, state policy initiatives should combine targeted higher education tuition subsidies with family support programs to foster intergenerational socio-economic mobility.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/olunna29\.github\.io\/final-project\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>